try
{
	a=2
	b=0
	if(b==0)
		throw "error"
	console.log(a/b)
}
catch (err)
{
	console.log(err)
}